#!/bin/bash
set -e
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

cd odoo_admin
if [[ -d /opt/wodoo ]]; then
	/opt/wodoo/test.py -xs ~/.cicd/settings "$@"
else
	odoo -xs ~/.cicd/settings "@"
fi

