{   'application': False,
    'assets': {},
    'auto_install': True,
    'data': [   'views/assets.xml',
                'views/branch_form.xml',
                'views/ticketsystem_form.xml',
                'security/ir.model.access.csv'],
    'demo': [],
    'depends': ['cicd'],
    'external_dependencies': {'python': ['jira']},
    'name': 'cicd',
    'qweb': [],
    'test': [],
    'version': '14.0.1.0'}
