{   'active': False,
    'application': False,
    'assets': {   'web.assets_backend': [   '/web_selenium/static/src/js/base_ext.js']},
    'author': 'Andreas Stauder <andreas.stauder@brain-tec.ch> and Alejandro '
              'Sanchez <alejandro.sanchez@braintec-group.com>',
    'bootstrap': True,
    'category': 'Hidden',
    'data': [],
    'demo': [],
    'depends': ['web'],
    'installable': True,
    'name': 'Web Selenium',
    'qweb': [   'static/src/xml/base_ext.xml',
                'static/src/xml/base_ext.xml',
                'static/src/xml/base_ext.xml'],
    'summary': 'Record your testcases with Selenium',
    'test': [],
    'version': '13.0.1.0.0',
    'web': True,
    'website': 'http://www.brain-tec.ch'}
