pipeline {
    agent any
    environment {
      BUILD_SCRIPTS='/opt/odoo-cicd-jenkins/build-scripts'
    }
    options { disableConcurrentBuilds() }
    stages {
      stage('Instance Kept') {
        steps {
          sh '''
          "$BUILD_SCRIPTS/run.py" build --key=kept 
          '''
        }
      }
      stage('Instance Demo') {
        steps {
          sh '''
          "$BUILD_SCRIPTS/run.py" build --key=demo 
          '''
        }
      }
      stage('Instance Live') {
        steps {
          sh '''
          "$BUILD_SCRIPTS/run.py" build --key=live 
          '''
        }
      }
    }
  }
